# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: "da"

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml

logger:
  default: error

lovelace:
  mode: yaml
  resources:
    - url: "/hacsfiles/button-card/button-card.js"
      type: module
    - url: "/hacsfiles/mini-media-player/mini-media-player-bundle.js"
      type: module
    - url: "/hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js"
      type: module
    - url: "/hacsfiles/mini-graph-card/mini-graph-card-bundle.js"
      type: module
    - url: "/hacsfiles/banner-card/banner-card.js"
      type: module
    - url: "/hacsfiles/lovelace-card-mod/card-mod.js"
      type: module
    - url: "/hacsfiles/lovelace-slider-entity-row/slider-entity-row.js"
      type: module
    - url: "/hacsfiles/lovelace-layout-card/layout-card.js"
      type: module
    - url: "/hacsfiles/weather-card/weather-card.js"
      type: module
    - url: "/hacsfiles/lovelace-buien-rain-card/buien-rain-card.js"
      type: module
    - url: "/hacsfiles/decluttering-card/decluttering-card.js"
      type: module
    - url: "/hacsfiles/text-element/text-element.js"
      type: module
    - url: "/hacsfiles/simple-weather-card/simple-weather-card-bundle.js"
      type: module
    - url: "/hacsfiles/kiosk-mode/kiosk-mode.js"
      type: module
    - url: "/hacsfiles/sidebar-card/sidebar-card.js"
      type: module
    - url: "/hacsfiles/stack-in-card/stack-in-card.js"
      type: module
    - url: "/hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js"
      type: module
