kiosk_mode:
  user_settings:
    - users:
        - "anneejsing"
        - "nicolajjensen"
      hide_sidebar: false
      hide_header: false
    - users:
        - "tablet"
      hide_sidebar: true
      hide_header: true
title: Home

sidebar: !include ui-elements/sidebar.yaml

views:
    - !include ui-elements/weather-view.yaml
